<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<StartupObject>SecureDocuments.Avalonia.Program</StartupObject>
		<FileVersion>0.9.8</FileVersion>
		<AssemblyVersion>0.9.8</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" Exclude="Assets\email_template.html" />
		<EmbeddedResource Include="Assets\email_template.html" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.2.6" />
		<PackageReference Include="Avalonia.Desktop" Version="11.2.6" />
		<PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.6" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.6" />
		<PackageReference Include="Material.Avalonia" Version="3.6.1" />
		<PackageReference Include="Material.Icons.Avalonia" Version="2.1.9" />
		<PackageReference Include="DialogHost.Avalonia" Version="0.10.0" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="14.7.1" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
		<PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="1.2.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Splat.Serilog" Version="14.4.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SecureDocuments\SecureDocuments.csproj" />
	</ItemGroup>

</Project>
